name: Docker build and push

on:
  release:
    types: [ published ]

env:
  DOCKER_IMAGE: 'rapita/demo-example-foo-svc'

jobs:
  build_and_push:
    name: Build and push image
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
          tags: type=semver,pattern=v{{version}}
          flavor: latest=true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}